// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCQ6TVru_JWSvof9c6BFUX8LoK7EUrhJEQ',
    appId: '1:1050702291065:web:5cdb4739ca2fa9f13334a8',
    messagingSenderId: '1050702291065',
    projectId: 'quick-cabs-d3951',
    authDomain: 'quick-cabs-d3951.firebaseapp.com',
    storageBucket: 'quick-cabs-d3951.firebasestorage.app',
    measurementId: 'G-H0NPJQBG3H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDiJyVdL_yn9cFuKqAybcZK-tzxrEx14dc',
    appId: '1:1050702291065:android:80fe939a887ff0e03334a8',
    messagingSenderId: '1050702291065',
    projectId: 'quick-cabs-d3951',
    storageBucket: 'quick-cabs-d3951.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBwOlSfGdu0q4SGrifc7m_JVJ7YRWZLoUk',
    appId: '1:1050702291065:ios:161c693ddc747c843334a8',
    messagingSenderId: '1050702291065',
    projectId: 'quick-cabs-d3951',
    storageBucket: 'quick-cabs-d3951.firebasestorage.app',
    iosBundleId: 'com.quickcabpune.quickcab',
  );
}
